@startuml

title Use Case Diagram

left to right direction

actor Продавець
rectangle "Програма" {
    usecase (Запакувати необхідну кількість води)
    usecase (Отримати кількість води)
    
    Продавець -- (Запакувати необхідну кількість води)
    Продавець -- (Отримати кількість води)
    (Отримати кількість води) <. (Запакувати необхідну кількість води) : include
}

@enduml
